apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: microservices-k8s
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
  # - image: sachinathu/microservices-book
  #   context: Books
  #   docker:
  #     dockerfile: Dockerfile.dev
  #   sync:
  #     infer:
  #       - '**/*.js'
  # - image: sachinathu/microservices-customer
  #   context: Customers
  #   docker:
  #     dockerfile: Dockerfile.dev
  #   sync:
  #     infer:
  #       - '**/*.js'
  - image: sachinathu/microservices-order
    context: Orders
    docker:
      dockerfile: Dockerfile.dev
    sync:
      infer:
        - '**/*.js'
deploy:
  kubectl:
    manifests:
      # - k8s/book-deployment.yaml
      # - k8s/customer-deployment.yaml
      - k8s/order-deployment.yaml