apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: book-service
  template:
    metadata:
      labels:
        component: book-service
    spec:
      containers:
        - name: microservice-book
          image: sachinathu/microservices-book
          ports:
            - containerPort: 4545
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongousername
                  key:  MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongopassword
                  key:  MONGO_PASSWORD
            - name: MONGO_HOST
              value: mongodb-node-port
            - name: MONGO_PORT
              value: '27017'