apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: customer-service
  template:
    metadata:
      labels:
        component: customer-service
    spec:
      containers:
        - name: microservice-customer
          image: sachinathu/microservices-customer
          ports:
            - containerPort: 5555
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongousername
                  key:  MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongopassword
                  key:  MONGO_PASSWORD
            - name: MONGO_HOST
              value: mongodb-node-port
            - name: MONGO_PORT
              value: '27017'