apiVersion: v1
kind: Service
metadata:
  name: customer-node-port
spec:
  type: NodePort
  ports:
    - port: 5555
      targetPort: 5555
      nodePort: 31055
  selector:
    component: customer-service